# Generated by Django 4.2.1 on 2023-05-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('e_mail', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('marital', models.CharField(max_length=255)),
                ('salary', models.FloatField()),
                ('available_vacation', models.IntegerField()),
                ('actual_approved_vacations', models.IntegerField()),
                ('date', models.CharField(max_length=255)),
            ],
        ),
    ]
