# Generated by Django 4.2.1 on 2023-05-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
    ]
