# Generated by Django 4.2.1 on 2023-06-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0005_vacations_rename_employee_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vacations',
        ),
    ]
