# Generated by Django 4.2.1 on 2023-06-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0007_vacations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='vacations',
        ),
    ]
