# Generated by Django 4.2.1 on 2023-06-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0008_delete_user_delete_vacations'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('e_mail', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('marital', models.CharField(max_length=255)),
                ('salary', models.FloatField()),
                ('available_vacation', models.IntegerField()),
                ('actual_approved_vacations', models.IntegerField()),
                ('date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='vacations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('vacation_duration', models.IntegerField()),
                ('From', models.CharField(max_length=255)),
                ('To', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('employee_name', models.CharField(max_length=255)),
            ],
        ),
    ]
