# Generated by Django 4.2.1 on 2023-06-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0010_rename_firstname_test_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
