# Generated by Django 4.2.1 on 2023-06-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0011_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
