# Generated by Django 4.2.1 on 2023-06-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0012_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
