# Generated by Django 4.2.1 on 2023-06-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0016_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacations',
            name='employee_id',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='vacations',
        ),
    ]
