# Generated by Django 4.2.1 on 2023-06-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0018_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.user'),
        ),
    ]
